package org.greenstand.android.TreeTracker.utilities


object ValueHelper {

    val NAME_SPACE = "org.greenstand.android"

    private val errorsOffset = 0
    val CONNECTION_FAILURE_RESOLUTION_REQUEST = errorsOffset + 1

    val SIGNUP_FRAGMENT = "SIGNUP_FRAGMENT"
    val LOGIN_FRAGMENT = "LOGIN_FRAGMENT"
    val MAP_FRAGMENT = "MAP_FRAGMENT"
    val NEW_TREE_FRAGMENT = "NEW_TREE_FRAGMENT"
    val FORGOT_PASSWORD_FRAGMENT = "FORGOT_PASSWORD_FRAGMENT"
    val HOME_FRAGMENT = "HOME_FRAGMENT"
    val DATA_FRAGMENT = "DATA_FRAGMENT"
    val SETTINGS_FRAGMENT = "SETTINGS_FRAGMENT"
    val ABOUT_FRAGMENT = "ABOUT_FRAGMENT"
    val UPDATE_TREE_FRAGMENT = "UPDATE_TREE_FRAGMENT"
    val TREE_PREVIEW_FRAGMENT = "TREE_PREVIEW_FRAGMENT"
    val EXIT_FRAGMENT = "EXIT_FRAGMENT"
    val NOTE_FRAGMENT = "NOTE_FRAGMENT"
    val UPDATE_TREE_DETAILS_FRAGMENT = "UPDATE_TREE_DETAILS_FRAGMENT"

    val SHOW_SIGNUP_FRAGMENT = "SHOW_SIGNUP_FRAGMENT"
    val SHOW_LOGIN_FRAGMENT = "SHOW_LOGIN_FRAGMENT"

    private val intentsOffset = 1000
    val INTENT_CAMERA = intentsOffset + 1

    /*MENU ITEMS*/
    val MENU_HOME = "MENU_HOME"
    val MENU_NEW_TREE = "MENU_NEW_TREE"
    val MENU_UPDATE_TREE = "MENU_UPDATE_TREE"
    val MENU_MAP = "MENU_MAP"
    val MENU_DATA = "MENU_DATA"
    val MENU_SETTINGS = "MENU_SETTINGS"
    val MENU_EXIT = "MENU_EXIT"


    val JPEG_FILE_PREFIX = "IMG_"
    val JPEG_FILE_SUFFIX = ".jpg"


    var SPLASH_SCREEN_DURATION: Long = 1000


    val TIME_TO_NEXT_UPDATE_GLOBAL_SETTING = "TIME_TO_NEXT_UPDATE_GLOBAL_SETTING"
    val TIME_TO_NEXT_UPDATE_ADMIN_DB_SETTING = "TIME_TO_NEXT_UPDATE_ADMIN_DB_SETTING"
    val TIME_TO_NEXT_UPDATE_ADMIN_DB_SETTING_PRESENT = "TIME_TO_NEXT_UPDATE_ADMIN_DB_SETTING_PRESENT"
    val MIN_ACCURACY_GLOBAL_SETTING = "MIN_ACCURACY_GLOBAL_SETTING"
    val MAIN_DB_USER_ID = "MAIN_DB_USER_ID"
    val MAIN_DB_NEXT_UPDATE = "MAIN_DB_NEXT_UPDATE"
    val MAIN_DB_MIN_ACCURACY = "MAIN_DB_MIN_ACCURACY"
    val MAIN_USER_ID = "MAIN_USER_ID"
    val MAIN_USER_FIRST_NAME = "MAIN_USER_FIRST_NAME"
    val MAIN_USER_LAST_NAME = "MAIN_USER_LAST_NAME"
    val TREE_ID = "TREE_ID"
    val TREE_PHOTO = "TREE_PHOTO"
    val PASSWORD = "PASSWORD"
    val USERNAME = "USERNAME"
    val TOKEN = "TOKEN"
    val TREE_TRACKER_SETTINGS_USED = "TREE_TRACKER_SETTINGS_USED"
    val FIRST_RUN = "FIRST_RUN"
    val SAVE_AND_EDIT = "SAVE_AND_EDIT"
    val TAKEN_IMAGE_PATH = "TAKEN_IMAGE_PATH"
    val RUN_FROM_NOTIFICATION_SYNC = "RUN_FROM_NOTIFICATION_SYNC"
    val RUN_FROM_HOME_ON_LOGIN = "RUN_FROM_HOME_ON_LOGIN"
    val TREES_TO_BE_DOWNLOADED_FIRST = "TREES_TO_BE_DOWNLOADED_FIRST"

    val TIME_TO_NEXT_UPDATE_DEFAULT_SETTING = 30
    val MIN_ACCURACY_DEFAULT_SETTING = 10
    val WIFI_NOTIFICATION_ID = 2000


}
